"""Bible story templates — 75+ interactive Bible stories spanning Genesis to Revelation.

Each template includes a scripture_reference and section field for organized display.
Templates are ordered by canonical book order within each testament.
"""

from app.tiers import StoryTemplate

BIBLE_TEMPLATES: list[StoryTemplate] = [
    # =========================================================================
    # OLD TESTAMENT — Genesis
    # =========================================================================
    StoryTemplate(
        title="Creation: God Makes the World",
        description="God creates the heavens, the earth, the animals, and the very first people in six amazing days.",
        emoji="🌍",
        prompt="In the very beginning, there was nothing but darkness. Then God spoke: 'Let there be light!' And suddenly, brilliant light burst across the emptiness. Day by day, God created something wonderful — the sky, the oceans, the land covered with flowers and trees, the sun and moon and stars, fish and birds and animals of every kind. And on the sixth day, God made something extra special — people! He formed Adam from the dust and breathed life into him. Then He made Eve. God looked at everything He had made and smiled. 'It is very good,' He said.",
        length="medium",
        scripture_reference="Genesis 1-2",
        section="Old Testament — Genesis",
    ),
    StoryTemplate(
        title="Adam and Eve in the Garden",
        description="Adam and Eve live in the beautiful Garden of Eden, but a sneaky serpent tempts them to disobey God.",
        emoji="🍎",
        prompt="Adam and Eve live in the most beautiful garden in the whole world — the Garden of Eden. There are sparkling rivers, fruit trees of every kind, and friendly animals everywhere. God tells them they can eat fruit from any tree except one — the Tree of the Knowledge of Good and Evil. 'You must not eat from that tree,' God says. But one day, a crafty serpent slithers up to Eve and whispers, 'Did God really say you can't eat from that tree? If you eat it, you'll be like God!' Eve looks at the fruit. It looks delicious...",
        length="medium",
        scripture_reference="Genesis 3",
        section="Old Testament — Genesis",
    ),
    StoryTemplate(
        title="Noah's Big Boat",
        description="God tells Noah to build an enormous boat and gather two of every animal before the great flood.",
        emoji="🚢",
        prompt="God looks down at the world and is sad. People have become very mean and unkind. But there is one man who still loves God — Noah. 'Noah,' God says, 'I am going to send a great flood to wash the earth clean. Build a big boat — an ark! Make it out of strong wood and seal it tight. Bring your family and two of every animal aboard.' Noah has never built a boat before, but he trusts God. His neighbors laugh. 'A boat? There's no water here!' But Noah keeps building. When the ark is finally ready, something amazing happens — animals start arriving from every direction.",
        length="medium",
        scripture_reference="Genesis 6-9",
        section="Old Testament — Genesis",
    ),
    StoryTemplate(
        title="The Tower of Babel",
        description="People try to build a tower all the way to heaven, but God has a different plan.",
        emoji="🏗️",
        prompt="After the great flood, Noah's family grows and grows. Soon there are many people living together, and they all speak the same language. 'Let's build a city!' they say. 'And a tower so tall it reaches the sky! Then everyone will know how great WE are!' They start building with bricks and tar, higher and higher. But God sees what they're doing. They're trying to make themselves as important as God. So God does something surprising — suddenly, the builders can't understand each other! One person says 'brick' and another hears something completely different. Confusion fills the building site.",
        length="medium",
        scripture_reference="Genesis 11:1-9",
        section="Old Testament — Genesis",
    ),
    StoryTemplate(
        title="Abraham's Big Journey",
        description="God calls Abraham to leave his home and travel to a new land, promising to make him the father of a great nation.",
        emoji="🐪",
        prompt="Abram lives in a city called Haran with his wife Sarai. One day, God speaks to him: 'Leave your country, your people, and your father's family. Go to the land I will show you. I will make you into a great nation and I will bless you.' Abram has never heard God speak before. He looks at Sarai. She looks back at him. They don't know where they're going or what they'll find. But Abram trusts God. He packs up his tents, gathers his flocks, and sets out on the greatest journey of his life — into the unknown.",
        length="medium",
        scripture_reference="Genesis 12:1-9",
        section="Old Testament — Genesis",
    ),
    StoryTemplate(
        title="Isaac Is Born: God Keeps His Promise",
        description="Abraham and Sarah are very old, but God promises them a baby — and God always keeps His promises.",
        emoji="👶",
        prompt="Abraham is ninety-nine years old. Sarah is ninety. They have waited and waited for the baby God promised, but no baby has come. One hot afternoon, three visitors arrive at Abraham's tent. 'About this time next year,' one of them says, 'Sarah will have a son.' Sarah is listening behind the tent flap. She laughs to herself — 'I'm way too old to have a baby!' The visitor asks, 'Is anything too hard for God?' And sure enough, just as God promised, a year later Sarah holds a tiny baby boy in her arms. They name him Isaac, which means 'laughter.'",
        length="medium",
        scripture_reference="Genesis 18:1-15; 21:1-7",
        section="Old Testament — Genesis",
    ),
    StoryTemplate(
        title="Jacob and Esau",
        description="Twin brothers Jacob and Esau are very different, and their rivalry leads to an adventure of forgiveness.",
        emoji="👬",
        prompt="Esau and Jacob are twin brothers, but they couldn't be more different. Esau is big, strong, and covered in red hair. He loves hunting in the wild. Jacob is quiet and clever, and he likes staying near the tents. One day, Esau comes home from hunting, exhausted and starving. Jacob is cooking a pot of delicious stew. 'Give me some of that stew!' Esau begs. Jacob sees an opportunity. 'I will — if you give me your birthright, your special blessing as the firstborn.' Esau is so hungry he doesn't think about what he's giving up. 'Fine! Take it!'",
        length="medium",
        scripture_reference="Genesis 25:19-34; 27; 33",
        section="Old Testament — Genesis",
    ),
    StoryTemplate(
        title="Joseph and the Colorful Coat",
        description="Joseph's father gives him a beautiful coat, but his jealous brothers have a terrible plan.",
        emoji="🧥",
        prompt="Jacob has twelve sons, but Joseph is his favorite. To show his love, Jacob gives Joseph a beautiful coat of many colors — reds, blues, golds, and purples. It's the most amazing coat anyone has ever seen. But Joseph's brothers are jealous. 'Why does he get a special coat and we don't?' they grumble. To make matters worse, Joseph has a dream that his brothers' bundles of grain bow down to his bundle. When he tells them about it, they are furious. 'You think you're better than us?' One day, Jacob sends Joseph to check on his brothers in the fields. As he approaches, they see the colorful coat coming over the hill...",
        length="long",
        scripture_reference="Genesis 37",
        section="Old Testament — Genesis",
    ),
    # =========================================================================
    # OLD TESTAMENT — Exodus through Deuteronomy
    # =========================================================================
    StoryTemplate(
        title="Baby Moses in the Basket",
        description="A brave mother hides her baby in a basket on the river, and a kind princess finds him.",
        emoji="🧺",
        prompt="In the land of Egypt, a brave mother holds her baby boy close. The mean pharaoh has ordered that all baby boys must be taken away, but she has a plan. She weaves a strong basket, coats it so no water can get in, and gently places her baby inside. She sets the basket among the tall reeds at the edge of the river. Baby Moses' big sister Miriam hides behind the bushes to watch. The basket floats gently on the water. Then — footsteps! The pharaoh's daughter, a kind princess, is coming to the river.",
        length="medium",
        scripture_reference="Exodus 2:1-10",
        section="Old Testament — Exodus",
    ),
    StoryTemplate(
        title="The Burning Bush",
        description="Moses sees a bush that is on fire but doesn't burn up, and God speaks to him from the flames.",
        emoji="🔥",
        prompt="Moses is watching over his father-in-law's sheep on a mountainside when he sees something very strange — a bush is on fire, but it isn't burning up! The flames dance and flicker, but the leaves stay green. Moses thinks, 'I have to go closer and see this amazing thing!' As he approaches, a voice calls from the bush: 'Moses! Moses!' Moses' heart pounds. 'Here I am,' he answers. 'Take off your sandals,' the voice says, 'for you are standing on holy ground. I am the God of your father Abraham.' God tells Moses He has heard His people crying in Egypt and has a very important job for Moses to do.",
        length="medium",
        scripture_reference="Exodus 3:1-15",
        section="Old Testament — Exodus",
    ),
    StoryTemplate(
        title="The Ten Plagues of Egypt",
        description="When Pharaoh refuses to let God's people go, God sends ten incredible signs to change his mind.",
        emoji="🐸",
        prompt="Moses stands before the mighty Pharaoh of Egypt. 'God says: Let my people go!' But Pharaoh laughs. 'Who is this God? I won't let them go!' So God sends signs to show His power. First, the river turns to blood — red and smelly! Then frogs everywhere — in the beds, in the ovens, hopping on Pharaoh's throne! Then gnats, then flies, then the animals get sick. Boils appear on everyone's skin. Hail crashes from the sky, locusts eat every plant, and thick darkness covers the land for three days. Each time Pharaoh says 'I'll let them go!' and then changes his mind.",
        length="long",
        scripture_reference="Exodus 7-11",
        section="Old Testament — Exodus",
    ),
    StoryTemplate(
        title="Crossing the Red Sea",
        description="With Pharaoh's army chasing them, God parts the Red Sea so His people can walk through on dry ground.",
        emoji="🌊",
        prompt="The Israelites are finally free! They march out of Egypt singing and dancing. But then they hear a terrible sound — the thunder of hooves and chariot wheels. Pharaoh changed his mind again and sent his whole army after them! The people are trapped — the Red Sea stretches before them and the army rushes up behind them. 'Don't be afraid!' Moses cries. 'Stand firm and you will see the Lord rescue you today!' Moses raises his staff over the sea. A mighty wind begins to blow. Slowly, incredibly, the waters begin to pull apart, rising up like walls on each side, revealing a dry path right through the middle of the sea.",
        length="medium",
        scripture_reference="Exodus 14",
        section="Old Testament — Exodus",
    ),
    StoryTemplate(
        title="The Ten Commandments",
        description="God calls Moses to the top of a mountain and gives him ten important rules for living.",
        emoji="⛰️",
        prompt="The Israelites camp at the foot of Mount Sinai. The mountain rumbles and shakes. Thick clouds cover the peak, and lightning flashes. A trumpet sound fills the air, growing louder and louder. God calls Moses to climb to the very top of the mountain. Moses climbs through the clouds, higher and higher, until he stands in the presence of God. There, God gives Moses ten special rules — the Ten Commandments — written on two stone tablets. 'Love Me with all your heart,' God says. 'And love the people around you. Don't steal, don't lie, honor your parents.' These rules will help the people live good and happy lives.",
        length="medium",
        scripture_reference="Exodus 19-20",
        section="Old Testament — Exodus",
    ),
    StoryTemplate(
        title="Manna from Heaven",
        description="God's people are hungry in the desert, but God sends special bread from the sky every morning.",
        emoji="🍞",
        prompt="The Israelites are wandering in the desert after leaving Egypt, and they're hungry. Very hungry. 'We wish we were back in Egypt!' they complain. 'At least we had food there!' God hears their grumbling and tells Moses, 'I will rain down bread from heaven for you. Each morning the people must go out and gather enough for that day.' The next morning, when the dew dries up, there on the ground is something thin and flaky, white like frost. 'What is it?' the people ask. Moses smiles. 'It is the bread the Lord has given you to eat.' They call it manna. It tastes like wafers made with honey.",
        length="short",
        scripture_reference="Exodus 16",
        section="Old Testament — Exodus",
    ),
    StoryTemplate(
        title="Balaam's Talking Donkey",
        description="A prophet's donkey sees an angel that the prophet can't see, and then the donkey speaks!",
        emoji="🫏",
        prompt="King Balak sends for Balaam, a prophet, and asks him to curse God's people. Balaam saddles his donkey and rides toward the Israelite camp. But God sends an angel with a sword to stand in the path! Balaam can't see the angel, but his donkey can. The donkey swerves off the road into a field. 'Get back on the road!' Balaam yells, hitting the donkey. The angel moves again, and the donkey presses against a wall, crushing Balaam's foot. Balaam hits her again. Finally, the donkey lies down completely. Balaam is furious — and then God does something amazing. He opens the donkey's mouth and she speaks! 'What have I done to you that you have hit me three times?'",
        length="medium",
        scripture_reference="Numbers 22:21-39",
        section="Old Testament — Numbers",
    ),
    StoryTemplate(
        title="Joshua and the Walls of Jericho",
        description="God tells Joshua to march around a mighty city, and the walls come tumbling down.",
        emoji="🎺",
        prompt="Joshua stands before the great walled city of Jericho. The gates are locked tight. The walls are thick and tall. No one goes in, and no one comes out. 'How will we ever get in?' the people wonder. But God tells Joshua a very unusual battle plan: 'March around the city once a day for six days. Seven priests shall carry trumpets in front of the ark. On the seventh day, march around the city seven times, and the priests shall blow the trumpets. When you hear the long trumpet blast, have all the people give a loud shout — and the walls will fall down!' It sounds impossible, but Joshua trusts God.",
        length="medium",
        scripture_reference="Joshua 6",
        section="Old Testament — Joshua",
    ),
    # =========================================================================
    # OLD TESTAMENT — Judges through Ruth
    # =========================================================================
    StoryTemplate(
        title="Deborah the Brave Judge",
        description="Deborah leads Israel with wisdom and courage, and helps defeat a powerful enemy army.",
        emoji="⚖️",
        prompt="In a time when Israel needs a leader, God raises up Deborah — a wise woman who sits under a palm tree and judges the people fairly. Everyone comes to her for advice. But Israel has a big problem: a cruel king named Jabin and his general Sisera have been bullying God's people for twenty years with nine hundred iron chariots! Deborah sends for a warrior named Barak. 'God commands you to take ten thousand men to Mount Tabor,' she says. 'God will hand Sisera over to you.' Barak says, 'I'll only go if you come with me.' Deborah stands tall. 'I will certainly go with you.'",
        length="medium",
        scripture_reference="Judges 4-5",
        section="Old Testament — Judges",
    ),
    StoryTemplate(
        title="Gideon's Tiny Army",
        description="God tells Gideon to fight a huge enemy army with only 300 soldiers, torches, and trumpets.",
        emoji="🏺",
        prompt="The Midianites are terrorizing Israel — a massive army that stretches across the valley like a swarm of locusts. God tells Gideon to fight them, but Gideon is nervous. 'I'm the weakest person in my family!' he says. God reassures him, but then does something surprising. Gideon gathers 32,000 soldiers, and God says, 'That's too many. I want Israel to know that I am the one who saves them.' After two rounds of thinning, Gideon is left with just 300 men! God's battle plan is wild: each soldier gets a trumpet, an empty jar, and a torch hidden inside the jar. In the middle of the night, they surround the enemy camp...",
        length="medium",
        scripture_reference="Judges 6-7",
        section="Old Testament — Judges",
    ),
    StoryTemplate(
        title="Samson the Strong",
        description="God gives Samson incredible strength, but Samson must learn that true strength comes from God.",
        emoji="💪",
        prompt="Samson is the strongest man who has ever lived. God gave him this amazing strength for a special purpose — to protect Israel from the Philistines. Samson can tear a lion apart with his bare hands! He can break ropes like they're thread! But there's a secret to his strength — his long hair, which he has never cut, is a sign of his promise to God. One day, a woman named Delilah keeps asking him, 'What makes you so strong?' The Philistines have offered her money to find out. Three times Samson gives her fake answers. But she keeps asking, day after day...",
        length="medium",
        scripture_reference="Judges 13-16",
        section="Old Testament — Judges",
    ),
    StoryTemplate(
        title="Ruth and Naomi: A Story of Loyalty",
        description="Ruth chooses to stay with her mother-in-law Naomi and discovers that loyalty and kindness lead to beautiful blessings.",
        emoji="🌾",
        prompt="Naomi is heartbroken. Her husband and both her sons have died, leaving her alone in a foreign land with her two daughters-in-law, Ruth and Orpah. 'Go back to your own families,' Naomi tells them, tears in her eyes. 'I have nothing left to offer you.' Orpah kisses Naomi goodbye and sadly walks away. But Ruth clings to Naomi and says the most beautiful words: 'Don't tell me to leave you. Where you go, I will go. Where you stay, I will stay. Your people will be my people and your God will be my God.' Together, the two women walk the long road back to Bethlehem, trusting God for their future.",
        length="medium",
        scripture_reference="Ruth 1-4",
        section="Old Testament — Ruth",
    ),
    # =========================================================================
    # OLD TESTAMENT — 1 Samuel through 2 Kings
    # =========================================================================
    StoryTemplate(
        title="Hannah's Prayer",
        description="Hannah prays with all her heart for a child, and God answers her prayer in a beautiful way.",
        emoji="🙏",
        prompt="Every year, Hannah travels to the tabernacle at Shiloh to worship God. But every year, her heart aches because she has no children. She watches other mothers holding their babies and cries. This year, Hannah can't hold back her tears. She goes to the tabernacle and prays silently, her lips moving but no sound coming out. She makes a promise to God: 'Lord, if you give me a son, I will give him back to you to serve you all the days of his life.' The priest Eli watches her and at first thinks something is wrong. But when Hannah explains, Eli says, 'Go in peace. May God give you what you have asked for.'",
        length="medium",
        scripture_reference="1 Samuel 1",
        section="Old Testament — 1 Samuel",
    ),
    StoryTemplate(
        title="Samuel Hears God's Voice",
        description="Young Samuel is sleeping in the tabernacle when he hears someone calling his name in the night.",
        emoji="👂",
        prompt="Young Samuel serves God in the tabernacle with the old priest Eli. One night, Samuel is lying down in his bed when he hears a voice: 'Samuel! Samuel!' He jumps up and runs to Eli. 'Here I am! You called me.' But Eli says, 'I didn't call you. Go back to bed.' Samuel lies down again. 'Samuel!' the voice calls again. Samuel runs to Eli again. 'Here I am!' Eli shakes his head. 'I didn't call you, my son.' When it happens a third time, old Eli realizes something amazing — it is the Lord who is calling the boy! 'Go lie down,' Eli says, 'and if He calls again, say: Speak, Lord, for your servant is listening.'",
        length="medium",
        scripture_reference="1 Samuel 3",
        section="Old Testament — 1 Samuel",
    ),
    StoryTemplate(
        title="David and Goliath",
        description="A brave shepherd boy named David faces the giant Goliath with nothing but faith and five smooth stones.",
        emoji="⚔️",
        prompt="The army of Israel is scared. Across the valley stands Goliath — a giant soldier so tall that his shadow covers the hillside. He's over nine feet tall, wearing bronze armor that gleams in the sun. Every day he shouts, 'Send someone to fight me! If he wins, we'll be your servants. If I win, you'll be ours!' For forty days, not a single soldier dares to step forward. Then young David arrives, bringing bread and cheese for his brothers. He hears Goliath's challenge and can't believe no one will fight him. 'Who is this man that he should defy the armies of the living God?' David says. He picks up five smooth stones from the stream and puts one in his sling.",
        length="medium",
        scripture_reference="1 Samuel 17",
        section="Old Testament — 1 Samuel",
    ),
    StoryTemplate(
        title="David and Jonathan: True Friendship",
        description="Prince Jonathan and shepherd David become the best of friends, even when it puts Jonathan in danger.",
        emoji="🤝",
        prompt="After David defeats Goliath, he meets Prince Jonathan, King Saul's son. Something special happens — they become best friends instantly. Jonathan gives David his own robe, his sword, his bow, and his belt. 'You are my best friend,' Jonathan says. But as David becomes more famous, King Saul grows jealous and wants to hurt David. Jonathan is caught in the middle — he loves his father, but David is his best friend. 'I'll find out if my father plans to harm you,' Jonathan promises David. They agree on a secret signal using arrows in a field. The next day, Jonathan shoots the arrows...",
        length="medium",
        scripture_reference="1 Samuel 18-20",
        section="Old Testament — 1 Samuel",
    ),
    StoryTemplate(
        title="Solomon's Wise Choice",
        description="When God offers young King Solomon anything he wants, Solomon makes the wisest choice of all.",
        emoji="👑",
        prompt="Young Solomon has just become king of Israel after his father David. It's a big job for someone so young! One night, God appears to Solomon in a dream and says something incredible: 'Ask for whatever you want me to give you.' Solomon could ask for piles of gold, or a huge army, or to live for a thousand years. But instead, Solomon says, 'Lord, I am like a little child. I don't know how to be a good king. Please give me a wise heart so I can tell the difference between right and wrong and lead your people well.' God is so pleased with Solomon's answer! 'Because you asked for wisdom instead of riches or long life, I will give you a wise heart — AND riches and honor too!'",
        length="medium",
        scripture_reference="1 Kings 3:1-15",
        section="Old Testament — 1 Kings",
    ),
    StoryTemplate(
        title="Elijah on Mount Carmel",
        description="The prophet Elijah challenges the prophets of a false god to a contest, and God answers with fire from heaven.",
        emoji="⚡",
        prompt="Israel is in trouble. King Ahab and Queen Jezebel have been leading the people to worship a false god called Baal. The prophet Elijah has had enough. He challenges all 450 prophets of Baal to a contest on Mount Carmel. 'Set up two altars with wood and a sacrifice,' Elijah says. 'You pray to your god, and I'll pray to mine. The god who answers with fire — He is the true God!' The prophets of Baal go first. They dance and shout from morning until noon: 'Baal, answer us!' Nothing happens. They shout louder. Still nothing. Then it's Elijah's turn. He pours water over his altar — not once, not twice, but three times, until water fills the trench around it.",
        length="medium",
        scripture_reference="1 Kings 18:16-40",
        section="Old Testament — 1 Kings",
    ),
    StoryTemplate(
        title="Elisha and Naaman's Healing",
        description="A mighty army general has a skin disease, and a little servant girl knows who can help.",
        emoji="💧",
        prompt="Naaman is the commander of the army of Aram — a powerful, important man. But he has a terrible skin disease called leprosy. A young Israelite girl who serves Naaman's wife says, 'If only my master could see the prophet in Samaria! He would heal him.' So Naaman travels to Israel with his horses and chariots and arrives at Elisha's house. But Elisha doesn't even come to the door! He sends a messenger who says, 'Go wash yourself seven times in the Jordan River, and you will be healed.' Naaman is furious! 'I expected him to wave his hand over me and call on God! The rivers back home are better than the Jordan!' He storms away. But his servants say, 'Sir, if the prophet had told you to do something hard, wouldn't you have done it?'",
        length="medium",
        scripture_reference="2 Kings 5:1-19",
        section="Old Testament — 2 Kings",
    ),
    StoryTemplate(
        title="Josiah Finds the Lost Book",
        description="Young King Josiah discovers God's lost Book of the Law in the temple and decides to follow God with all his heart.",
        emoji="📜",
        prompt="Josiah becomes king of Judah when he is only eight years old! Even though he's young, Josiah loves God. When he grows up, he notices that God's temple is falling apart. 'Repair the temple!' he orders. While the workers are cleaning and fixing, the high priest Hilkiah finds something amazing hidden in the dusty walls — the Book of the Law that Moses wrote long ago! When Josiah hears the words read aloud, he tears his clothes in sadness. The people have not been following God's commands at all! 'We must change our ways,' Josiah declares. He gathers all the people — from the youngest to the oldest — and reads the entire book to them.",
        length="medium",
        scripture_reference="2 Kings 22-23",
        section="Old Testament — 2 Kings",
    ),
    # =========================================================================
    # OLD TESTAMENT — Ezra through Esther
    # =========================================================================
    StoryTemplate(
        title="Rebuilding God's Temple",
        description="After years away from home, God's people return to Jerusalem and rebuild the temple with joy.",
        emoji="🏛️",
        prompt="For seventy long years, God's people have been far from home, living in Babylon. But now King Cyrus of Persia says, 'Go home! Rebuild the temple of your God!' Ezra leads thousands of people on the long journey back to Jerusalem. When they arrive, their hearts break — the beautiful temple is just a pile of rubble. But they don't give up. They lay a new foundation, and when it's finished, the priests blow trumpets and everyone shouts for joy! Some of the old people who remember the first temple cry because they know how glorious it once was. But the young people shout with happiness because something new is beginning.",
        length="medium",
        scripture_reference="Ezra 1-6",
        section="Old Testament — Ezra",
    ),
    StoryTemplate(
        title="Nehemiah Rebuilds the Wall",
        description="Nehemiah leaves a comfortable job to rebuild Jerusalem's broken walls, and the people work together with swords and trowels.",
        emoji="🧱",
        prompt="Nehemiah serves as the cupbearer to King Artaxerxes — a very important and comfortable job. But when he hears that Jerusalem's walls are still broken and the gates are burned, he sits down and cries. He prays to God for help. The king notices Nehemiah's sad face and asks what's wrong. Nehemiah bravely explains, and the king gives him permission to go rebuild! When Nehemiah arrives in Jerusalem, he rides around the city at night to see the damage. Then he gathers the people. 'Let us rebuild the wall!' Enemies try to stop them through threats and tricks, but the workers hold a tool in one hand and a sword in the other.",
        length="medium",
        scripture_reference="Nehemiah 1-6",
        section="Old Testament — Nehemiah",
    ),
    StoryTemplate(
        title="Esther Saves Her People",
        description="Queen Esther must find the courage to speak up and save her people from a terrible plan.",
        emoji="👸",
        prompt="Esther is a young Jewish woman living in Persia who becomes queen! But she has kept a secret — no one in the palace knows she is Jewish. Then a wicked man named Haman convinces the king to make a law that will destroy all the Jewish people. Esther's cousin Mordecai sends her an urgent message: 'You must go to the king and beg for mercy for our people!' But there's a problem — anyone who approaches the king without being invited could be killed. Esther is afraid. Mordecai tells her, 'Who knows? Perhaps you were made queen for such a time as this.' Esther makes her decision: 'I will go to the king. And if I perish, I perish.'",
        length="medium",
        scripture_reference="Esther 1-10",
        section="Old Testament — Esther",
    ),
    # =========================================================================
    # OLD TESTAMENT — Job through Psalms
    # =========================================================================
    StoryTemplate(
        title="Job's Incredible Faith",
        description="Job loses everything but never stops trusting God, and learns that God is always with him.",
        emoji="🕊️",
        prompt="Job is a good man who loves God. He has a big family, lots of animals, and a beautiful home. But then terrible things start happening — his animals are stolen, his servants are hurt, and a great wind destroys the house where his children are gathered. Job is heartbroken. Then he gets painful sores all over his body. His wife says, 'Give up on God!' His friends come and say, 'You must have done something wrong!' But Job says, 'The Lord gave and the Lord has taken away. Blessed be the name of the Lord.' Even when everything goes wrong, Job keeps trusting God. He doesn't understand why bad things are happening, but he believes God is still good.",
        length="medium",
        scripture_reference="Job 1-2; 42",
        section="Old Testament — Job",
    ),
    StoryTemplate(
        title="The Good Shepherd (Psalm 23)",
        description="King David writes a beautiful song about how God takes care of us like a loving shepherd.",
        emoji="🐑",
        prompt="David the shepherd boy sits on a green hillside watching his sheep. He thinks about how he takes care of them — leading them to soft grass and cool water, protecting them from wolves and lions, finding them when they wander off. Then David realizes something wonderful: God takes care of me the same way! He picks up his harp and begins to sing: 'The Lord is my shepherd, I have everything I need. He lets me lie down in green pastures. He leads me beside quiet waters. He gives me new strength.' As David plays, the sheep gather close, the stars begin to appear, and the whole hillside fills with peaceful music.",
        length="short",
        scripture_reference="Psalm 23",
        section="Old Testament — Psalms",
    ),
    StoryTemplate(
        title="Wonderfully Made (Psalm 139)",
        description="A song about how God knows you completely and made you absolutely wonderful.",
        emoji="✨",
        prompt="Close your eyes and imagine something amazing: before you were born, God already knew you! He knew every thought you would think, every word you would say, every step you would take. King David writes about this in a beautiful song: 'Lord, you have searched me and you know me. You know when I sit down and when I get up. You know what I'm going to say even before I say it!' David looks at his own hands and is amazed. 'I praise you because you made me in an amazing and wonderful way. Everything you do is wonderful. I know that very well.' No matter where you go — up to the highest mountain or down to the deepest sea — God is there with you.",
        length="short",
        scripture_reference="Psalm 139",
        section="Old Testament — Psalms",
    ),
    # =========================================================================
    # OLD TESTAMENT — Prophets
    # =========================================================================
    StoryTemplate(
        title="Isaiah's Amazing Vision",
        description="The prophet Isaiah has an incredible vision of God's throne room and volunteers to be God's messenger.",
        emoji="🕊️",
        prompt="In the year that King Uzziah dies, the prophet Isaiah has a vision that takes his breath away. He sees the Lord sitting on a throne, high and lifted up, and the train of His robe fills the entire temple! Above the throne fly angels called seraphim, each with six wings. They call to one another: 'Holy, holy, holy is the Lord Almighty! The whole earth is full of His glory!' The doorposts shake, the temple fills with smoke, and Isaiah falls to his knees. 'I'm not worthy to see this!' he cries. But an angel touches his lips with a coal from the altar. 'Your sins are forgiven.' Then God asks, 'Whom shall I send?' Isaiah answers bravely: 'Here am I. Send me!'",
        length="medium",
        scripture_reference="Isaiah 6",
        section="Old Testament — Isaiah",
    ),
    StoryTemplate(
        title="Jeremiah: The Brave Young Prophet",
        description="God calls a young man named Jeremiah to be His prophet, even though Jeremiah thinks he's too young.",
        emoji="📢",
        prompt="God speaks to a young man named Jeremiah: 'Before I formed you in your mother's body I chose you. Before you were born I set you apart. I appointed you to be a prophet to the nations.' Jeremiah is afraid. 'But Lord,' he says, 'I'm just a child! I don't know how to speak to important people!' But God reaches out and touches Jeremiah's mouth. 'Don't be afraid of them, for I am with you. I have put my words in your mouth.' God shows Jeremiah a branch from an almond tree, blooming with pink flowers in winter, and says, 'I am watching to see that my word comes true.' Jeremiah will have a hard job — telling people things they don't want to hear — but God promises to be with him every step of the way.",
        length="medium",
        scripture_reference="Jeremiah 1",
        section="Old Testament — Jeremiah",
    ),
    StoryTemplate(
        title="Ezekiel and the Valley of Dry Bones",
        description="God shows Ezekiel a valley full of dry bones and asks an incredible question: 'Can these bones live?'",
        emoji="💀",
        prompt="God's Spirit carries the prophet Ezekiel to a valley. When Ezekiel looks around, he can't believe his eyes — the valley is full of dry bones, scattered everywhere. They are very dry. God asks Ezekiel an amazing question: 'Son of man, can these bones live?' Ezekiel answers wisely: 'Lord God, only you know.' God says, 'Speak to these bones. Tell them: Dry bones, hear the word of the Lord!' Ezekiel opens his mouth and speaks God's words. Suddenly, there's a rattling sound. The bones start moving — connecting together! Then muscles and skin appear. But there's no breath in them. God says, 'Now speak to the wind: Come from the four winds, O breath, and breathe into these bodies!'",
        length="medium",
        scripture_reference="Ezekiel 37:1-14",
        section="Old Testament — Ezekiel",
    ),
    StoryTemplate(
        title="Daniel in the Lions' Den",
        description="Daniel is thrown into a den of hungry lions, but God sends an angel to keep him safe all night.",
        emoji="🦁",
        prompt="Daniel loves God and prays to Him three times every day, kneeling at his window facing Jerusalem. But the king has signed a new law: for thirty days, no one can pray to anyone except the king. Anyone who disobeys will be thrown to the lions! Daniel knows about the law, but he also knows that God is more important than any king's decree. He kneels by his window and prays, just like always. The jealous officials catch him and bring him to King Darius, who is very sad — he likes Daniel! But the law cannot be changed. Daniel is lowered into the deep pit of hungry lions. The king calls down, 'May your God rescue you!' A heavy stone seals the entrance.",
        length="medium",
        scripture_reference="Daniel 6",
        section="Old Testament — Daniel",
    ),
    StoryTemplate(
        title="The Fiery Furnace",
        description="Three friends refuse to bow to a golden statue and are thrown into a blazing furnace — but they're not alone inside.",
        emoji="🔥",
        prompt="King Nebuchadnezzar builds an enormous golden statue and commands everyone to bow down and worship it. When the music plays, everyone must fall to their knees — or be thrown into a blazing furnace! But three young men — Shadrach, Meshach, and Abednego — refuse to bow. They stand tall while everyone else falls down. The king is furious. 'Is it true you won't worship my statue?' he demands. The three friends answer bravely: 'The God we serve is able to save us from your furnace. But even if He doesn't, we want you to know that we will never worship your golden statue.' The king orders the furnace heated seven times hotter than usual and has the three friends thrown in.",
        length="medium",
        scripture_reference="Daniel 3",
        section="Old Testament — Daniel",
    ),
    StoryTemplate(
        title="Jonah and the Big Fish",
        description="Jonah tries to run away from God and ends up inside an enormous fish.",
        emoji="🐋",
        prompt="God tells Jonah to go to the great city of Nineveh and warn the people to stop being wicked. But Jonah doesn't want to go! The people of Nineveh are Israel's enemies. Instead, Jonah boards a ship sailing the opposite direction — as far from Nineveh as he can get. But you can't run from God. A terrible storm rocks the boat, waves crash over the sides, and the sailors are terrified. Jonah knows the storm is because he ran away. 'Throw me into the sea,' he tells the sailors, 'and the storm will stop.' They do, and SPLASH — the sea goes calm. But then a massive shadow rises from below. An enormous fish opens its mouth wide and swallows Jonah whole!",
        length="medium",
        scripture_reference="Jonah 1-4",
        section="Old Testament — Jonah",
    ),
    # =========================================================================
    # NEW TESTAMENT — Birth and Early Life of Jesus
    # =========================================================================
    StoryTemplate(
        title="An Angel Visits Mary",
        description="The angel Gabriel brings an amazing message to a young woman named Mary that will change the world forever.",
        emoji="👼",
        prompt="In the small town of Nazareth, a young woman named Mary is going about her day when suddenly, an angel appears before her! His name is Gabriel, and he glows with heavenly light. Mary is startled and afraid. 'Don't be afraid, Mary,' Gabriel says gently. 'God is pleased with you. You will have a baby boy, and you will call him Jesus. He will be great and will be called the Son of the Most High God. His kingdom will never end.' Mary is confused. 'How can this be?' she asks. Gabriel answers, 'The Holy Spirit will come upon you. Nothing is impossible with God.' Mary takes a deep breath and says, 'I am the Lord's servant. Let it happen as you have said.'",
        length="medium",
        scripture_reference="Luke 1:26-38",
        section="New Testament — Luke",
    ),
    StoryTemplate(
        title="The First Christmas",
        description="Baby Jesus is born in a humble stable in Bethlehem on the most special night the world has ever known.",
        emoji="⭐",
        prompt="Mary and Joseph have traveled a long way to Bethlehem. Mary is about to have her baby, and they need a place to stay. But when they reach the town, every inn is full. 'No room! No room!' everyone says. Finally, a kind innkeeper sees how tired Mary is. 'I don't have a room, but you can use my stable.' In that humble place, surrounded by gentle animals, the most important baby in the history of the world is born. Mary wraps him in soft cloths and lays him in a manger — a feeding box for animals — because there is no crib. She looks at his tiny face and whispers his name: Jesus.",
        length="medium",
        scripture_reference="Luke 2:1-7",
        section="New Testament — Luke",
    ),
    StoryTemplate(
        title="Shepherds and Angels",
        description="Angels appear to shepherds on a hillside with the most exciting news ever: the Savior has been born!",
        emoji="🌟",
        prompt="It's the middle of the night. Shepherds are watching their flocks on the dark hillside near Bethlehem. Everything is quiet except for the gentle bleating of sheep. Then suddenly — LIGHT! An angel of the Lord appears, and the glory of God shines all around them, brighter than a thousand suns! The shepherds are terrified! 'Don't be afraid!' the angel says. 'I bring you good news that will bring great joy to all people. Today in the town of Bethlehem, a Savior has been born to you — He is the Messiah, the Lord! You will find the baby wrapped in cloths and lying in a manger.' Then the whole sky fills with angels, singing: 'Glory to God in the highest heaven!'",
        length="medium",
        scripture_reference="Luke 2:8-20",
        section="New Testament — Luke",
    ),
    StoryTemplate(
        title="The Wise Men Follow a Star",
        description="Wise men from the East follow a special star on a long journey to find the newborn King.",
        emoji="🌠",
        prompt="Far away in the East, wise men who study the stars notice something they have never seen before — a brand new star, brighter than all the others, hanging in the western sky. They know what it means: a great king has been born! They pack precious gifts — gold, frankincense, and myrrh — and set off on a long journey to find this special child. They travel for months, following the star across deserts and mountains. When they arrive in Jerusalem, they ask, 'Where is the one who has been born king of the Jews? We saw his star when it rose and have come to worship him.' The star leads them onward, all the way to a small house in Bethlehem.",
        length="medium",
        scripture_reference="Matthew 2:1-12",
        section="New Testament — Matthew",
    ),
    StoryTemplate(
        title="Boy Jesus at the Temple",
        description="Twelve-year-old Jesus amazes the teachers at the temple with His understanding and questions.",
        emoji="🏛️",
        prompt="Every year, Mary and Joseph take Jesus to Jerusalem for the Passover festival. This year, Jesus is twelve years old. After the festival, the big group starts the long walk home. Mary and Joseph assume Jesus is walking with friends and relatives. But after a whole day of traveling, they can't find Him anywhere! Panicked, they rush back to Jerusalem and search for three days. Finally, they find Jesus in the temple, sitting among the teachers, listening to them and asking questions. Everyone who hears Him is amazed at His understanding. 'Son!' Mary says, upset. 'We've been searching everywhere for you!' Jesus looks up, surprised. 'Didn't you know I had to be in my Father's house?'",
        length="medium",
        scripture_reference="Luke 2:41-52",
        section="New Testament — Luke",
    ),
    # =========================================================================
    # NEW TESTAMENT — Miracles of Jesus
    # =========================================================================
    StoryTemplate(
        title="Water into Wine",
        description="At a wedding party, Jesus performs His very first miracle — turning water into the best wine anyone has ever tasted.",
        emoji="🍷",
        prompt="Jesus and His disciples are invited to a wedding in a town called Cana. Everyone is celebrating — music is playing, people are dancing, and there's a big feast. But then something embarrassing happens: the wine runs out! Mary, Jesus' mother, comes to Him. 'They have no more wine,' she says. Then she tells the servants, 'Do whatever He tells you.' Jesus sees six large stone water jars nearby, each one big enough to hold twenty or thirty gallons. 'Fill those jars with water,' Jesus says. The servants fill them to the brim. 'Now draw some out and take it to the master of the banquet.' When the master tastes it, his eyes go wide — it's wine, and it's the best wine he's ever tasted!",
        length="medium",
        scripture_reference="John 2:1-11",
        section="New Testament — John",
    ),
    StoryTemplate(
        title="Jesus Calms the Storm",
        description="A terrifying storm threatens to sink the disciples' boat, but Jesus speaks three words that change everything.",
        emoji="⛵",
        prompt="Jesus and His disciples are crossing the Sea of Galilee in a small boat. Jesus is so tired that He falls asleep on a cushion in the back. Suddenly, a furious storm sweeps across the lake. Waves crash over the sides of the boat. Water pours in. The wind howls. The disciples — some of them experienced fishermen — are terrified. They think they're going to drown! They shake Jesus awake. 'Teacher, don't you care if we drown?' Jesus stands up in the rocking boat, faces the raging wind and churning waves, and says three calm words: 'Quiet! Be still!' Instantly — the wind stops. The waves smooth out. Everything is perfectly calm.",
        length="medium",
        scripture_reference="Mark 4:35-41",
        section="New Testament — Mark",
    ),
    StoryTemplate(
        title="Feeding the Five Thousand",
        description="A huge crowd is hungry, and all anyone can find is one boy's tiny lunch — but Jesus makes it enough for everyone.",
        emoji="🍞",
        prompt="Five thousand people have gathered on a hillside to hear Jesus teach and to be healed. As evening comes, the disciples realize there's a problem — all these people are hungry, and they're far from any town. 'Send the people away to buy food,' the disciples suggest. Jesus says, 'You give them something to eat.' The disciples look at each other. 'That would take eight months' wages!' Andrew finds a boy in the crowd who has a small lunch: five barley loaves and two small fish. 'But what good is this among so many people?' Jesus smiles. 'Have everyone sit down.' He takes the bread and fish, looks up to heaven, and gives thanks.",
        length="medium",
        scripture_reference="John 6:1-14",
        section="New Testament — John",
    ),
    StoryTemplate(
        title="Walking on Water",
        description="In the middle of the night on a stormy sea, Jesus walks across the water to His frightened friends.",
        emoji="🌊",
        prompt="After feeding the five thousand, Jesus tells His disciples to get in the boat and cross the lake while He goes up on a mountainside alone to pray. By the middle of the night, the boat is far from shore, battered by the waves. The wind is against them. Suddenly the disciples see a figure walking toward them — on top of the water! 'It's a ghost!' they scream. But Jesus calls out, 'Take courage! It is I. Don't be afraid.' Peter shouts back, 'Lord, if it's you, tell me to come to you on the water!' Jesus says one word: 'Come.' Peter steps out of the boat — and walks on the water toward Jesus!",
        length="medium",
        scripture_reference="Matthew 14:22-33",
        section="New Testament — Matthew",
    ),
    StoryTemplate(
        title="Jesus Heals the Blind Man",
        description="A man who has been blind since birth receives his sight in the most unexpected way.",
        emoji="👁️",
        prompt="As Jesus walks along the road, He sees a man who has been blind from birth. He has never seen a sunrise, never seen a flower, never seen the faces of the people he loves. The disciples ask, 'Teacher, who sinned that this man was born blind?' Jesus answers, 'Nobody sinned. This happened so that God's power could be shown in his life.' Then Jesus does something surprising — He spits on the ground, makes mud with the dirt, and puts it on the man's eyes. 'Go wash in the Pool of Siloam,' Jesus says. The blind man walks to the pool, kneels down, and splashes the cool water on his face. When he opens his eyes for the very first time...",
        length="medium",
        scripture_reference="John 9:1-11",
        section="New Testament — John",
    ),
    StoryTemplate(
        title="Jesus Raises Lazarus",
        description="Jesus' dear friend Lazarus has died and been buried for four days, but Jesus has the power to give life.",
        emoji="🪦",
        prompt="Jesus receives terrible news: His dear friend Lazarus is very sick. But instead of rushing to help, Jesus waits two more days. By the time Jesus arrives in Bethany, Lazarus has been in the tomb for four days. Martha, Lazarus' sister, runs to meet Jesus. 'Lord, if you had been here, my brother would not have died.' Jesus says, 'Your brother will rise again.' Martha thinks He means someday in the future. But Jesus says, 'I am the resurrection and the life. Anyone who believes in me will live, even though they die.' Standing at the tomb, Jesus weeps — He loved Lazarus dearly. Then He says, 'Take away the stone.' He looks up and prays, then shouts with a loud voice: 'Lazarus, come out!'",
        length="medium",
        scripture_reference="John 11:1-44",
        section="New Testament — John",
    ),
    # =========================================================================
    # NEW TESTAMENT — Parables of Jesus
    # =========================================================================
    StoryTemplate(
        title="The Good Samaritan",
        description="Jesus tells a story about a kind stranger who stops to help when everyone else walks by.",
        emoji="❤️",
        prompt="Someone asks Jesus, 'Who is my neighbor?' So Jesus tells a story: 'A man was traveling from Jerusalem to Jericho when robbers attacked him. They beat him up, took his clothes, and left him lying on the road, barely alive. A priest came walking by — surely he would help! But the priest looked at the hurt man and walked by on the other side. Then a Levite, a temple helper, came along. He also looked at the hurt man and walked by. But then a Samaritan came along — someone that most people in Israel didn't even like. When he saw the hurt man, his heart was filled with compassion. He knelt down, bandaged his wounds, put him on his own donkey, and took him to an inn to rest.'",
        length="short",
        scripture_reference="Luke 10:25-37",
        section="New Testament — Luke",
    ),
    StoryTemplate(
        title="The Prodigal Son",
        description="A young man takes his inheritance, wastes it all, and discovers that his father's love is waiting for him when he comes home.",
        emoji="🏠",
        prompt="Jesus tells a story about a father with two sons. The younger son says, 'Father, give me my share of the money now.' The father, though sad, gives it to him. The young man travels far away and spends all his money on foolish things. When a famine comes, he has nothing left. He's so hungry he takes a job feeding pigs and wishes he could eat their food. Sitting in the mud, he thinks, 'My father's servants have food to spare, and here I am starving!' He decides to go home and say, 'Father, I have sinned. I'm not worthy to be called your son. Let me be one of your servants.' He begins the long walk home, his head hanging low. But while he's still far away, his father sees him coming...",
        length="medium",
        scripture_reference="Luke 15:11-32",
        section="New Testament — Luke",
    ),
    StoryTemplate(
        title="The Lost Sheep",
        description="Jesus tells the story of a shepherd who leaves ninety-nine sheep to find the one that wandered away.",
        emoji="🐑",
        prompt="Jesus is surrounded by tax collectors and sinners who have come to hear Him. The Pharisees and teachers of the law are grumbling: 'This man welcomes sinners and eats with them!' So Jesus tells them a story: 'Imagine you're a shepherd with one hundred sheep. You count them at the end of the day — ninety-seven, ninety-eight, ninety-nine... only ninety-nine! One little lamb is missing! What do you do? You leave the ninety-nine safe sheep in the open field and go searching for the one that is lost. You look behind every rock, in every thorny bush, near every stream. Then you hear it — a tiny, scared baaaa! You find the little lamb caught in a thicket, shivering and afraid.'",
        length="short",
        scripture_reference="Luke 15:1-7",
        section="New Testament — Luke",
    ),
    StoryTemplate(
        title="The Mustard Seed",
        description="Jesus teaches that even the tiniest seed of faith can grow into something big and amazing.",
        emoji="🌱",
        prompt="The disciples ask Jesus, 'What is the kingdom of heaven like?' Jesus picks up something tiny between His thumb and finger — a mustard seed, one of the smallest seeds in all the garden. 'The kingdom of heaven is like this mustard seed,' Jesus says. 'A farmer plants it in his field. It is the smallest of all seeds. But when it grows, it becomes the biggest plant in the garden — so big that it becomes a tree, and the birds of the air come and make their nests in its branches!' The disciples look at the tiny seed and try to imagine it becoming a great tree. Jesus is teaching them that even a little bit of faith — a faith as small as a mustard seed — can grow into something wonderful.",
        length="short",
        scripture_reference="Matthew 13:31-32",
        section="New Testament — Matthew",
    ),
    StoryTemplate(
        title="The Wise and Foolish Builders",
        description="Jesus tells a story about two men who build houses — one on solid rock and one on shifting sand.",
        emoji="🏗️",
        prompt="Jesus says, 'Everyone who hears my words and puts them into practice is like a wise man who built his house on the rock.' Imagine two builders: the wise man searches until he finds a big, solid rock. He digs deep and lays his foundation right on that rock. It takes longer, but he knows it will last. The foolish man wants to finish quickly. He finds a nice flat stretch of sand and builds his house right there — no digging, no foundation, nice and easy! Both houses look great on sunny days. But then the rain comes down, the streams rise, and the winds blow and beat against the houses. The house on the sand wobbles, creaks, and CRASH — it falls with a mighty splash! But the house on the rock? It doesn't move even a little.",
        length="short",
        scripture_reference="Matthew 7:24-27",
        section="New Testament — Matthew",
    ),
    StoryTemplate(
        title="The Ten Bridesmaids",
        description="Jesus tells a story about ten young women waiting for a wedding — but only five are ready when the groom arrives.",
        emoji="🪔",
        prompt="Jesus tells a story about being ready: 'Ten young women take their oil lamps and go out to meet the groom for a wedding feast. Five of them are wise and five are foolish. The wise ones bring extra oil for their lamps. The foolish ones don't bother. The groom takes a long time to come, and all ten women fall asleep. At midnight, a shout rings out: He's coming! He's coming! All ten women wake up and trim their lamps. But the foolish women's lamps are sputtering out — they have no oil left! They beg the wise women, Share your oil with us! But there isn't enough for everyone. While the foolish women run to buy more oil, the groom arrives. The wise women go into the wedding feast, and the door is shut.'",
        length="short",
        scripture_reference="Matthew 25:1-13",
        section="New Testament — Matthew",
    ),
    # =========================================================================
    # NEW TESTAMENT — Holy Week and Resurrection
    # =========================================================================
    StoryTemplate(
        title="The Triumphal Entry",
        description="Jesus rides into Jerusalem on a donkey while crowds wave palm branches and shout with joy.",
        emoji="🌿",
        prompt="It's almost Passover, and Jesus is heading to Jerusalem. He sends two disciples ahead: 'Go to the village. You'll find a young donkey tied there. Untie it and bring it to me.' They find the donkey just as Jesus said. Jesus rides the donkey toward Jerusalem. As He approaches the city, something amazing starts to happen. People begin to spread their cloaks on the road like a carpet. Others cut branches from palm trees and wave them in the air. The whole crowd starts shouting: 'Hosanna! Blessed is He who comes in the name of the Lord! Hosanna in the highest heaven!' The ground shakes with their joyful noise. Children are dancing and singing. It feels like the whole world is celebrating.",
        length="medium",
        scripture_reference="Matthew 21:1-11",
        section="New Testament — Matthew",
    ),
    StoryTemplate(
        title="The Last Supper",
        description="On His last night with His friends, Jesus shares a special meal and teaches them about love.",
        emoji="🍷",
        prompt="It is the evening of Passover, and Jesus gathers His twelve closest friends in an upstairs room for a special meal. Before they eat, Jesus does something that surprises everyone — He wraps a towel around His waist, pours water into a basin, and begins to wash His disciples' feet. 'I am your teacher and Lord,' Jesus says, 'yet I have washed your feet. You should wash one another's feet too. I have given you an example.' During the meal, Jesus takes bread, gives thanks, breaks it, and shares it. 'This is my body, given for you. Do this to remember me.' Then He takes a cup. 'This is my blood, poured out for many for the forgiveness of sins.' The room grows quiet. Something very important is happening.",
        length="medium",
        scripture_reference="Matthew 26:17-30; John 13:1-17",
        section="New Testament — Matthew",
    ),
    StoryTemplate(
        title="The Garden of Gethsemane",
        description="Jesus prays alone in a garden the night before the most important day in history.",
        emoji="🌙",
        prompt="After the supper, Jesus goes with His disciples to a garden called Gethsemane. 'Sit here while I pray,' He tells them. He takes Peter, James, and John further in. Jesus' heart is heavy with sadness. He knows what is going to happen tomorrow. He falls to the ground and prays, 'Father, if it is possible, take this cup of suffering from me. Yet not what I want, but what you want.' He prays so hard that drops of sweat fall like blood. He goes back to His three friends — and they're asleep! 'Couldn't you keep watch with me for one hour?' He prays again, pouring out His heart to His Father. Then the sound of footsteps and torches approaches through the darkness.",
        length="medium",
        scripture_reference="Matthew 26:36-46",
        section="New Testament — Matthew",
    ),
    StoryTemplate(
        title="The Cross and the Empty Tomb",
        description="Jesus gives the greatest gift of all on the cross, and three days later, the most wonderful surprise in history.",
        emoji="✝️",
        prompt="Jesus is taken away by soldiers. He is treated very badly. He carries a heavy wooden cross up a hill called Golgotha. There, Jesus is put on the cross. Even in His pain, Jesus prays, 'Father, forgive them. They don't know what they're doing.' The sky turns dark in the middle of the day. Jesus calls out, 'It is finished.' And then He dies. His friends are heartbroken. They gently take His body down and lay it in a tomb carved from rock, rolling a heavy stone across the entrance. On Sunday morning, some women come to the tomb. But the stone has been rolled away! The tomb is empty! An angel in white says the most amazing words in all of history: 'He is not here — He has risen!'",
        length="medium",
        scripture_reference="Matthew 27:32-28:10",
        section="New Testament — Matthew",
    ),
    StoryTemplate(
        title="The Road to Emmaus",
        description="Two sad travelers meet a stranger on the road who opens their eyes to the most wonderful truth.",
        emoji="🚶",
        prompt="It's the afternoon of the very first Easter. Two of Jesus' followers are walking sadly on the road from Jerusalem to a village called Emmaus, about seven miles away. They're talking about everything that happened — Jesus' death, the empty tomb, the angels. A stranger joins them on the road. 'What are you talking about?' He asks. 'Are you the only visitor to Jerusalem who doesn't know what happened?' one of them says. They tell the stranger all about Jesus. The stranger begins to explain the scriptures to them, starting with Moses and all the prophets. Their hearts burn with excitement! When they reach Emmaus, the stranger sits down to eat with them. He takes the bread, gives thanks, and breaks it — and suddenly their eyes are opened. 'It's Jesus!'",
        length="medium",
        scripture_reference="Luke 24:13-35",
        section="New Testament — Luke",
    ),
    # =========================================================================
    # NEW TESTAMENT — Acts and Early Church
    # =========================================================================
    StoryTemplate(
        title="Pentecost: The Holy Spirit Comes",
        description="The Holy Spirit arrives like wind and fire, and the disciples speak in languages they've never learned.",
        emoji="🔥",
        prompt="After Jesus goes back to heaven, He tells His friends to wait in Jerusalem for a special gift. About 120 believers gather in an upstairs room, praying and waiting. Then, on the day of Pentecost, it happens! A sound like a powerful rushing wind fills the whole house. Something that looks like tongues of fire appears and rests on each person. They are all filled with the Holy Spirit — and they begin to speak in different languages they've never learned! People from all over the world are in Jerusalem for the festival. They hear the noise and come running. They're amazed! 'How can these Galileans speak our languages?' Peter stands up boldly and explains what's happening. That day, about 3,000 people believe in Jesus!",
        length="medium",
        scripture_reference="Acts 2:1-41",
        section="New Testament — Acts",
    ),
    StoryTemplate(
        title="Peter's Amazing Vision",
        description="God gives Peter a strange vision of a sheet full of animals to teach him that His love is for everyone.",
        emoji="🍽️",
        prompt="Peter goes up on the roof to pray. He's hungry, and while lunch is being prepared, he falls into a trance. He sees heaven open and something like a large sheet coming down, held by its four corners. Inside the sheet are all kinds of animals — animals that Jewish people consider unclean and would never eat. A voice says, 'Get up, Peter. Kill and eat.' Peter is shocked! 'No, Lord! I have never eaten anything impure or unclean!' The voice speaks again: 'Do not call anything impure that God has made clean.' This happens three times! While Peter is wondering what the vision means, messengers arrive at his door from a Roman centurion named Cornelius. God is teaching Peter something revolutionary: His love and salvation is for ALL people, not just Jewish people.",
        length="medium",
        scripture_reference="Acts 10:1-48",
        section="New Testament — Acts",
    ),
    StoryTemplate(
        title="Paul's Dramatic Conversion",
        description="Saul hates the followers of Jesus — until a blinding light on the road to Damascus changes everything.",
        emoji="⚡",
        prompt="Saul is a man on a mission — and not a good one. He hates the followers of Jesus and wants to arrest every single one of them. He gets special permission from the high priest and sets off for Damascus, breathing threats against the believers. But as he approaches the city, a brilliant light from heaven suddenly flashes around him — brighter than the sun! Saul falls to the ground. A voice speaks: 'Saul, Saul, why are you persecuting me?' 'Who are you, Lord?' Saul asks, trembling. 'I am Jesus, whom you are persecuting.' When Saul opens his eyes, he can't see — the light has blinded him. His companions lead him by the hand into Damascus, where he sits in darkness for three days, not eating or drinking.",
        length="medium",
        scripture_reference="Acts 9:1-19",
        section="New Testament — Acts",
    ),
    StoryTemplate(
        title="Paul and Silas in Prison",
        description="Paul and Silas are beaten and chained in a dark prison, but they start singing — and God sends an earthquake.",
        emoji="⛓️",
        prompt="Paul and Silas are thrown into the deepest, darkest part of the prison in Philippi. Their backs are bloody from being beaten, and their feet are locked in heavy wooden stocks. It's cold, it's dark, and it hurts. But instead of crying or complaining, Paul and Silas do something amazing — they start praying and singing hymns to God! At midnight, their voices echo through the stone corridors. The other prisoners listen in silence. Then suddenly, the ground shakes violently — a powerful earthquake! The prison doors fly open and everyone's chains fall off! The jailer wakes up, sees the open doors, and thinks all the prisoners have escaped. But Paul shouts, 'Don't harm yourself! We are all here!'",
        length="medium",
        scripture_reference="Acts 16:16-40",
        section="New Testament — Acts",
    ),
    StoryTemplate(
        title="Paul's Shipwreck Adventure",
        description="Paul is on a ship heading to Rome when a terrible storm batters the vessel for two whole weeks.",
        emoji="🚢",
        prompt="Paul is a prisoner being taken to Rome by ship. He warns the centurion, 'This voyage is going to be dangerous.' But nobody listens. Soon, a violent storm called a northeaster sweeps across the sea. For two weeks — fourteen days! — the ship is battered by the storm. They can't see the sun or the stars. The sailors throw cargo overboard. Everyone gives up hope. But an angel appears to Paul in the night: 'Don't be afraid, Paul. God has graciously given you the lives of all who sail with you.' Paul tells everyone, 'Keep up your courage! Not one of you will be lost — only the ship.' On the fourteenth night, the sailors sense they're near land. The ship hits a sandbar and begins to break apart in the pounding waves.",
        length="medium",
        scripture_reference="Acts 27",
        section="New Testament — Acts",
    ),
    # =========================================================================
    # NEW TESTAMENT — Epistles and Revelation
    # =========================================================================
    StoryTemplate(
        title="The Armor of God",
        description="Paul teaches about the special armor God gives us to stand strong against anything — the armor of truth, love, and faith.",
        emoji="🛡️",
        prompt="The apostle Paul is writing a letter to his friends in Ephesus from prison. He wants them to be brave and strong in their faith. 'Be strong in the Lord and in His mighty power,' Paul writes. 'Put on the full armor of God!' He describes each piece: the Belt of Truth — always be honest. The Breastplate of Righteousness — do what is right and it will protect your heart. The Shoes of Peace — be ready to share the good news wherever you go. The Shield of Faith — it can stop every fiery arrow the enemy sends. The Helmet of Salvation — protect your mind with the truth that God saved you. And the Sword of the Spirit — God's Word, the only weapon you need!",
        length="short",
        scripture_reference="Ephesians 6:10-18",
        section="New Testament — Ephesians",
    ),
    StoryTemplate(
        title="The Greatest Is Love",
        description="Paul writes the most beautiful description of love ever written — and it changes how we understand what love really means.",
        emoji="💝",
        prompt="Paul writes a letter to the church in Corinth about something more important than any gift or talent: love. 'If I speak in the tongues of angels but don't have love, I'm just a noisy gong. If I have faith that can move mountains but don't have love, I am nothing.' Then Paul describes what real love looks like: 'Love is patient. Love is kind. It does not envy. It does not boast. It is not proud. It does not dishonor others. It is not selfish. It is not easily angered. It keeps no record of wrongs. Love does not delight in evil but rejoices with the truth. It always protects, always trusts, always hopes, always perseveres.' And the most beautiful part: 'Love never fails.'",
        length="short",
        scripture_reference="1 Corinthians 13",
        section="New Testament — 1 Corinthians",
    ),
    StoryTemplate(
        title="A New Heaven and a New Earth",
        description="John sees a vision of the beautiful new world God is preparing — where there will be no more tears or sadness.",
        emoji="🌈",
        prompt="The apostle John is very old now, living on a small island called Patmos. God gives him an incredible vision of the future. John sees a brand new heaven and a brand new earth — more beautiful than anything anyone has ever imagined! A great city, the New Jerusalem, comes down from heaven, shining like a precious jewel. And then John hears a loud voice from God's throne: 'Look! God's home is now among His people. He will live with them, and they will be His people.' The most wonderful promise follows: 'God will wipe away every tear from their eyes. There will be no more death or mourning or crying or pain, for the old order of things has passed away.' The city needs no sun or moon — God's glory is its light!",
        length="medium",
        scripture_reference="Revelation 21-22",
        section="New Testament — Revelation",
    ),
    # =========================================================================
    # Additional stories to reach 75+
    # =========================================================================
    StoryTemplate(
        title="The Baptism of Jesus",
        description="Jesus comes to the Jordan River to be baptized by John, and heaven opens with God's voice.",
        emoji="🕊️",
        prompt="People from all over Israel are coming to the Jordan River to be baptized by John the Baptist. John wears clothes made of camel hair and eats locusts and wild honey. He preaches, 'Turn away from your sins! The kingdom of heaven is near!' One day, Jesus walks up to the river's edge. John looks at Him and knows — this is the one he's been waiting for! 'I need to be baptized by you,' John says, 'and you come to me?' Jesus answers gently, 'Let it be so now. It is right for us to do this.' John agrees and baptizes Jesus in the cool water. As Jesus comes up out of the river, heaven opens! The Spirit of God comes down like a dove and lands on Jesus. And a voice from heaven says, 'This is my Son, and I love Him. I am very pleased with Him.'",
        length="medium",
        scripture_reference="Matthew 3:13-17",
        section="New Testament — Matthew",
    ),
    StoryTemplate(
        title="Zacchaeus the Tax Collector",
        description="A very short man climbs a tree just to see Jesus — and gets the surprise of his life.",
        emoji="🌳",
        prompt="Zacchaeus is a tax collector in Jericho, and nobody likes him. He charges people too much money and keeps the extra for himself. He's very rich but very lonely. When he hears that Jesus is passing through town, something stirs in his heart. He wants to see Jesus! But there's a problem — Zacchaeus is very short, and the crowd is thick. He can't see over anyone's head. So he does something that a rich, important man would never normally do — he runs ahead and climbs a sycamore-fig tree! He perches on a branch, waiting. When Jesus walks by, He stops right under the tree. He looks up and says, 'Zacchaeus, come down immediately! I must stay at your house today.'",
        length="short",
        scripture_reference="Luke 19:1-10",
        section="New Testament — Luke",
    ),
    StoryTemplate(
        title="Jesus and the Children",
        description="The disciples try to send the children away, but Jesus says the kingdom of heaven belongs to them.",
        emoji="👧",
        prompt="Parents are bringing their little children to Jesus, hoping He will place His hands on them and bless them. But the disciples try to stop them. 'Don't bother the Teacher!' they say. 'He's too important to spend time with children!' When Jesus sees this, He is upset with His disciples. 'Let the little children come to me!' He says. 'Don't keep them away! The kingdom of heaven belongs to people who are like these children.' Then Jesus opens His arms wide. The children run to Him — climbing on His lap, tugging His robe, showing Him their treasures. Jesus picks up a small child, smiles, and places His hands on each one, blessing them. The children giggle with joy.",
        length="short",
        scripture_reference="Mark 10:13-16",
        section="New Testament — Mark",
    ),
    StoryTemplate(
        title="The Widow's Small Coins",
        description="Everyone gives large gifts at the temple, but Jesus says a poor widow's two tiny coins are worth the most.",
        emoji="🪙",
        prompt="Jesus sits near the temple treasury, watching people put their offerings into the collection box. Rich people come and drop in large amounts of money — clink, clink, clink! — making sure everyone can see their generosity. Then a poor widow walks quietly to the box. She's wearing worn clothes and looks tired. She reaches into her pocket and drops in two tiny copper coins — the smallest coins there are, worth almost nothing. Nobody notices. But Jesus calls His disciples over. 'I tell you the truth,' Jesus says, pointing to the widow. 'This poor widow has put more into the treasury than all the others. They gave out of their wealth, but she gave out of her poverty — everything she had to live on.'",
        length="short",
        scripture_reference="Mark 12:41-44",
        section="New Testament — Mark",
    ),
    StoryTemplate(
        title="Philip and the Ethiopian",
        description="An angel sends Philip on a desert road where he meets a man reading the Bible in his chariot — but the man needs help understanding it.",
        emoji="📖",
        prompt="An angel tells Philip, 'Go south to the desert road from Jerusalem to Gaza.' Philip doesn't know why, but he goes. On the road, he sees a fancy chariot carrying an important Ethiopian official who is in charge of the queen's treasury. The man is reading aloud from the scroll of the prophet Isaiah! The Holy Spirit tells Philip, 'Go to that chariot and stay near it.' Philip runs alongside and hears the man reading: 'He was led like a sheep to be killed...' Philip asks, 'Do you understand what you're reading?' The Ethiopian smiles sadly. 'How can I, unless someone explains it to me? Please, come sit with me.' Philip climbs into the chariot and begins to explain that Isaiah was writing about Jesus.",
        length="medium",
        scripture_reference="Acts 8:26-40",
        section="New Testament — Acts",
    ),
    StoryTemplate(
        title="The Healing at the Beautiful Gate",
        description="Peter and John meet a man who can't walk at the temple gate, and Peter offers him something better than money.",
        emoji="🚶",
        prompt="Peter and John are going to the temple at three in the afternoon for prayer. At the gate called Beautiful, there sits a man who has not been able to walk his entire life. Every day, his friends carry him to this spot so he can beg for money. When he sees Peter and John, he asks them for some coins. Peter looks straight at the man and says, 'Look at us!' The man looks up eagerly, expecting money. But Peter says, 'Silver and gold I do not have — but what I do have, I give to you. In the name of Jesus Christ of Nazareth, get up and walk!' Peter reaches down and takes the man by the right hand and helps him up. Instantly, the man's feet and ankles become strong!",
        length="medium",
        scripture_reference="Acts 3:1-10",
        section="New Testament — Acts",
    ),
]
